### ISSUE TITLE
 Constraint universe:modules

### ISSUE THREAD

**Issue by JWDobken** [vazco/meteor-universe-react-widgets#2]
I would like to use the react-widgets in meteor. Is this package my best shot?

When I run `meteor add universe:react-widgets` I get:

    Constraint universe:modules@0.6.4 is not satisfied by universe:modules 0.1.0

I updated all my NPM packages (`meteor npm update`)

**Comment by cristo-rabani** [comment]
Hello, this package is abandonware. 
Please install react-widgets from npm `meteor npm install - - save react-widgets `

**Comment by JWDobken** [comment]
Ah the package works!

But how to set-up the styling? the package advice is to set-up webpack, but I'm in meteor!

**Comment by JWDobken** [comment]
import 'react-widgets/dist/css/react-widgets.css';

thanks a lot!

Still I don't get the awesome icons, but I will figure it out
